# Generated by Django 4.2 on 2024-11-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
