# Generated by Django 4.2 on 2024-11-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookLog', '0002_alter_book_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='books',
        ),
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
