# Generated by Django 4.2 on 2024-11-20 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookLog', '0003_rename_book_books_alter_books_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowers',
            fields=[
                ('borrower_id', models.AutoField(primary_key=True, serialize=False)),
                ('borrower_name', models.CharField(max_length=30)),
                ('active_book_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'borrowers',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='borrow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('return_status', models.BooleanField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookLog.books')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookLog.borrowers')),
            ],
            options={
                'db_table': 'loan',
            },
        ),
    ]
