# Generated by Django 4.2 on 2024-11-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookLog', '0004_borrowers_books_borrow_count_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='borrower',
            new_name='borrower_id',
        ),
    ]
