# Generated by Django 4.2 on 2024-11-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookLog', '0006_rename_book_id_loan_books_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='books',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='borrowers',
            new_name='borrower',
        ),
    ]
